import { stableJson,type UploadBatch,type LegacyHandoffResult } from '../../../shared/sync-v3';
import { initialContext } from '../../../shared/usage-domain/normalize';
import { TOKEN_FIELDS,type Candidate,type ThreadChange } from '../../../shared/usage-domain/types';
import type { SyncManifest } from '../../../shared/usage-sync';
import { fail,sha256 } from '../http';
import type { CandidateRow } from './apply';
import { advanceHead,chunks,domain,endGuard,entityStatements,guard,type Domain,type WriteDevice } from './store';
import { advanceRebuild,rebuildCleanup,rebuildPublication,stageCandidateStatements,stageSourceStatements,type RebuildCheckpoint } from './rebuild';
import { prepareProjectMetadata } from './projects';
import type { Job } from './jobs';

type LegacyHead={user_id:string;device_id:string;dataset_id:string;thread_id:string;revision:number;manifest:string;collector_id:string;source_id:string};
type LegacyPayload={head:LegacyHead;project_id:string|null;project_name:string|null};
const sourceId=async(dataset:string,thread:string)=>'legacy:'+await sha256(stableJson([dataset,thread]));
export async function prepareHandoff(db:D1Database,h:Domain,device:WriteDevice,b:UploadBatch) {
  const plans:{collector_id:string;source_id:string;generation:number;payload:null}[]=[],statements:D1PreparedStatement[]=[],outcomes:LegacyHandoffResult[]=[];
  for(const m of b.metadata)if(m.type==='legacy_replacement'){
    const head=await db.prepare('SELECT h.revision,l.collector_id,l.source_id,l.retired_revision FROM usage_heads h LEFT JOIN v3_legacy_heads l USING(user_id,device_id,dataset_id,thread_id) WHERE h.user_id=? AND h.device_id=? AND h.dataset_id=? AND h.thread_id=?').bind(h.user_id,device.id,m.dataset_id,m.thread_id).first<{revision:number;collector_id:string|null;source_id:string|null;retired_revision:number|null}>();
    if(!head||(head.retired_revision||0)>=head.revision){outcomes.push({dataset_id:m.dataset_id,thread_id:m.thread_id,status:'applied'});continue;}
    const sourceRows=(await db.prepare(`SELECT source_id,generation,active,complete,available,context FROM v3_sources WHERE user_id=? AND collector_id=? AND source_id IN(SELECT value FROM json_each(?))`).bind(h.user_id,b.collector_id,stableJson(m.sources.map(s=>s.source_id))).all<{source_id:string;generation:number;active:number;complete:number;available:number;context:string}>()).results;
    // An immutable backfill handoff may be overtaken by a newer source on the live lane.
    // Acknowledge the obsolete operation without publishing it or blocking later lane progress.
    if(m.sources.some(s=>sourceRows.some(r=>r.source_id===s.source_id&&r.generation>s.generation))){outcomes.push({dataset_id:m.dataset_id,thread_id:m.thread_id,status:'superseded'});continue;}
    if(m.sources.some(s=>!sourceRows.some(r=>r.source_id===s.source_id&&r.generation===s.generation&&r.complete===1&&r.available===1&&JSON.parse(r.context).thread_id===m.thread_id)))fail(409,'LEGACY_REPLACEMENT_INCOMPLETE','旧历史替换必须等待对应原始来源完整应用。');
    outcomes.push({dataset_id:m.dataset_id,thread_id:m.thread_id,status:'applied'});
    const collector=head.collector_id||'legacy:'+device.id,source=head.source_id||await sourceId(m.dataset_id,m.thread_id);plans.push({collector_id:collector,source_id:source,generation:-1,payload:null});
    for(const replacement of m.sources){
      if(!plans.some(p=>p.collector_id===b.collector_id&&p.source_id===replacement.source_id))plans.push({collector_id:b.collector_id,...replacement,payload:null});
      // Candidates were durably applied but private until the old head and complete replacements switch together.
      statements.push(db.prepare('UPDATE v3_sources SET active=0 WHERE user_id=? AND collector_id=? AND source_id=?').bind(h.user_id,b.collector_id,replacement.source_id));
      for(const table of ['v3_sources','v3_candidates'])statements.push(db.prepare(`UPDATE ${table} SET active=CASE WHEN generation=? THEN 1 ELSE 0 END WHERE user_id=? AND collector_id=? AND source_id=?`).bind(replacement.generation,h.user_id,b.collector_id,replacement.source_id));
    }
    statements.push(db.prepare(`INSERT INTO v3_legacy_heads(user_id,device_id,dataset_id,thread_id,retired_revision,collector_id,source_id) VALUES(?,?,?,?,?,?,?) ON CONFLICT(user_id,device_id,dataset_id,thread_id) DO UPDATE SET retired_revision=MAX(retired_revision,excluded.retired_revision)`).bind(h.user_id,device.id,m.dataset_id,m.thread_id,head.revision,collector,source));
    for(const table of ['v3_candidates','v3_observations','v3_source_threads','v3_deferred_records','v3_dependencies','v3_sources'])statements.push(db.prepare(`DELETE FROM ${table} WHERE user_id=? AND collector_id=? AND source_id=?`).bind(h.user_id,collector,source));
  }
  return {plans,statements,outcomes};
}
function insertStagedCandidates(db:D1Database,user:string,job:string):D1PreparedStatement {
  const fields=['observation_id','uploader_device_id','collector_id','source_id','generation','record_revision','event_id','thread_id','turn_id','at','signature','candidate','origin_claim'];
  return db.prepare(`INSERT INTO v3_candidates(user_id,${fields.join(',')},active) SELECT user_id,${fields.map(k=>`json_extract(payload,'$.${k}')`).join(',')},1 FROM v3_rebuild_candidates WHERE user_id=? AND job_id=? AND payload IS NOT NULL`).bind(user,job);
}
async function resetLegacyJob(db:D1Database,h:Domain,job:Job,epoch:string) {
  const op=crypto.randomUUID();await db.batch([guard(db,h,op,undefined,job),...['v3_events','v3_entity_versions','v3_aggregates','v3_aggregate_members'].map(t=>db.prepare(`DELETE FROM ${t} WHERE user_id=? AND epoch=? AND epoch<>?`).bind(h.user_id,epoch,h.active_epoch)),...rebuildCleanup(db,h.user_id,job.job_id),db.prepare("UPDATE v3_sync_domains SET mode=CASE WHEN mode='rebuilding' THEN 'ready' ELSE mode END,rebuild_job=NULL,write_version=write_version+1 WHERE user_id=? AND rebuild_job=?").bind(h.user_id,job.job_id),db.prepare("UPDATE v3_jobs SET payload='{}',checkpoint='{}',state='pending',lease_token=NULL,lease_until=0,next_attempt_at=0 WHERE user_id=? AND job_id=?").bind(h.user_id,job.job_id),endGuard(db,h.user_id,op)]);
}
/** Import only committed heads. Unknown execution origin and source-position identity remain explicit. */
export async function legacyStep(db:D1Database,job:Job):Promise<boolean> {
  const h=await domain(db,job.user_id),saved=JSON.parse(job.payload) as Partial<LegacyPayload>;
  if(!saved.head){
    if(h.mode!=='ready')return false;
    const next=await db.prepare(`SELECT h.*,r.manifest FROM usage_heads h JOIN usage_revisions r USING(user_id,device_id,dataset_id,thread_id,revision) JOIN devices d ON d.id=h.device_id LEFT JOIN v3_legacy_heads l USING(user_id,device_id,dataset_id,thread_id)
      WHERE h.user_id=? AND r.committed=1 AND d.history_deleted_at IS NULL AND h.revision>COALESCE(l.imported_revision,0) AND h.revision>COALESCE(l.retired_revision,0) ORDER BY h.device_id,h.dataset_id,h.thread_id LIMIT 1`).bind(job.user_id).first<LegacyHead>();
    const op=crypto.randomUUID();if(!next){await db.batch([guard(db,h,op,undefined,job),db.prepare('UPDATE v3_sync_domains SET legacy_baseline_pending=0,write_version=write_version+1 WHERE user_id=?').bind(h.user_id),db.prepare("UPDATE v3_jobs SET state='complete',lease_token=NULL,lease_until=0,updated_at=? WHERE user_id=? AND job_id=?").bind(Date.now(),job.user_id,job.job_id),endGuard(db,h.user_id,op)]);return true;}
    const head={...next,collector_id:'legacy:'+next.device_id,source_id:await sourceId(next.dataset_id,next.thread_id)},m=JSON.parse(head.manifest) as SyncManifest,projectId=m.thread.project?'legacy-project:'+await sha256(m.thread.project):null,context={...initialContext(head.thread_id),cwd:m.thread.project,source_project_id:projectId},thread:ThreadChange={id:head.thread_id,title:m.thread.title,title_updated_at:m.thread.titleUpdatedAt,project:m.thread.project,source_project_id:projectId?'pc1:'+await sha256(stableJson([head.collector_id,projectId])):null,source:m.thread.source,parent_id:m.thread.parentId,subagent_parent_id:m.thread.subagentParentId,forked_from_id:m.thread.forkedFromId};
    const source={user_id:h.user_id,collector_id:head.collector_id,source_id:head.source_id,generation:head.revision,kind:'session',cursor:m.eventCount,snapshot_eof:m.eventCount,context_hash:await sha256(stableJson(context)),context:stableJson(context),legacy_state:null,active:1,complete:1,available:1,trailing_bytes:0};
    await db.batch([guard(db,h,op,undefined,job),db.prepare('INSERT INTO v3_collectors(user_id,collector_id,device_id,created_at) VALUES(?,?,?,?) ON CONFLICT DO NOTHING').bind(h.user_id,head.collector_id,head.device_id,Date.now()),...stageSourceStatements(db,h.user_id,job.job_id,[{collector_id:head.collector_id,source_id:head.source_id,generation:head.revision,payload:stableJson(source)}]),db.prepare('INSERT INTO v3_rebuild_threads(user_id,job_id,collector_id,source_id,generation,thread_id,payload) VALUES(?,?,?,?,?,?,?)').bind(h.user_id,job.job_id,head.collector_id,head.source_id,head.revision,head.thread_id,stableJson(thread)),db.prepare("UPDATE v3_jobs SET payload=?,checkpoint=?,state='pending',lease_token=NULL,lease_until=0,next_attempt_at=0 WHERE user_id=? AND job_id=?").bind(stableJson({head,project_id:projectId,project_name:m.thread.project}),stableJson({phase:'import',epoch:crypto.randomUUID(),last:''}),h.user_id,job.job_id),db.prepare("UPDATE v3_sync_domains SET mode='rebuilding',rebuild_job=?,write_version=write_version+1 WHERE user_id=?").bind(job.job_id,h.user_id),endGuard(db,h.user_id,op)]);return false;
  }
  const p=saved as LegacyPayload,head=p.head,c=JSON.parse(job.checkpoint) as {phase:string;epoch:string;last?:string},current=await db.prepare('SELECT h.revision FROM usage_heads h JOIN devices d ON d.id=h.device_id WHERE h.user_id=? AND h.device_id=? AND h.dataset_id=? AND h.thread_id=? AND d.history_deleted_at IS NULL').bind(h.user_id,head.device_id,head.dataset_id,head.thread_id).first<number>('revision');
  if(current!==head.revision){await resetLegacyJob(db,h,job,c.epoch);return false;}
  if(h.mode!=='rebuilding'||h.rebuild_job!==job.job_id){await resetLegacyJob(db,h,job,c.epoch);return false;}
  if(c.phase==='import'){
    const rows=(await db.prepare(`SELECT event_key,thread_id,turn_id,response_id,at,project,model,effort,kind,incomplete,${TOKEN_FIELDS.map(f=>`CAST(${f} AS TEXT) ${f}`).join(',')} FROM usage_records WHERE user_id=? AND device_id=? AND dataset_id=? AND thread_id=? AND revision=? AND event_key>? ORDER BY event_key LIMIT 200`).bind(h.user_id,head.device_id,head.dataset_id,head.thread_id,head.revision,c.last||'').all<Record<string,any>>()).results,map=new Map<string,CandidateRow|null>();
    for(const r of rows){const observation=await sha256(stableJson(['v2',head.device_id,head.dataset_id,head.thread_id,head.revision,r.event_key])),event=r.response_id?'response:'+r.response_id:'v2:'+await sha256(stableJson([head.device_id,head.dataset_id,head.thread_id,r.event_key])),candidate:Candidate={...Object.fromEntries(TOKEN_FIELDS.map(f=>[f,r[f]])),observation_id:observation,record_revision:1,source_id:head.source_id,generation:head.revision,event_id:event,thread_id:r.thread_id,turn_id:r.turn_id,response_id:r.response_id,at:r.at,project:r.project,source_project_id:p.project_id,model:r.model,effort:r.effort,kind:r.kind,signature:null,incomplete:!!r.incomplete,excluded:false,identity_quality:r.response_id?'response':'source_position',origin:{device_id:null,kind:'unknown'}} as Candidate;
      map.set(observation,{observation_id:observation,uploader_device_id:head.device_id,collector_id:head.collector_id,source_id:head.source_id,generation:head.revision,record_revision:1,event_id:event,thread_id:r.thread_id,turn_id:r.turn_id,at:r.at,signature:null,active:1,candidate:stableJson(candidate)});}
    if(rows.length)c.last=rows.at(-1)!.event_key;else {c.phase='events';delete c.last;}
    const op=crypto.randomUUID();await db.batch([guard(db,h,op,undefined,job),...stageCandidateStatements(db,h.user_id,job.job_id,map),db.prepare("UPDATE v3_jobs SET checkpoint=?,state='pending',lease_token=NULL,lease_until=0,next_attempt_at=0 WHERE user_id=? AND job_id=?").bind(stableJson(c),h.user_id,job.job_id),endGuard(db,h.user_id,op)]);return false;
  }
  return advanceRebuild(db,job,async(live,checkpoint)=>{
    const source=await db.prepare('SELECT payload FROM v3_rebuild_sources WHERE user_id=? AND job_id=? AND collector_id=? AND source_id=?').bind(h.user_id,job.job_id,head.collector_id,head.source_id).first<string>('payload'),s=JSON.parse(source!),context=JSON.parse(s.context),fake:UploadBatch={protocol:3,schema_version:1,extractor_version:1,collector_id:head.collector_id,producer_epoch:'legacy',lane:'backfill',lane_seq:1,batch_id:'legacy',records_hash:'',records:[],sources:[{source_id:s.source_id,generation:s.generation,kind:'session',from_cursor:0,to_cursor:s.cursor,snapshot_eof:s.snapshot_eof,context_hash:s.context_hash,context,replace_start:true,replace_end:true,generation_complete:true,available:true,trailing_bytes:0}],metadata:p.project_id?[{type:'project',source_project_id:p.project_id,value:{kind:'unresolved',name:p.project_name,root:p.project_name,reason:'legacy-path'}}]:[]},projects=await prepareProjectMetadata(db,live,fake,head.device_id),target={...live,active_epoch:checkpoint.epoch,commit_seq:0},op=crypto.randomUUID(),statements:D1PreparedStatement[]=[guard(db,live,op,undefined,job)];
    for(const t of ['v3_candidates','v3_source_threads','v3_sources'])statements.push(db.prepare(`DELETE FROM ${t} WHERE user_id=? AND collector_id=? AND source_id=?`).bind(h.user_id,head.collector_id,head.source_id));
    const sourceFields=['collector_id','source_id','generation','kind','cursor','snapshot_eof','context_hash','context','legacy_state','active','complete','available','trailing_bytes'];
    statements.push(db.prepare(`INSERT INTO v3_sources(user_id,${sourceFields.join(',')}) VALUES(?,${sourceFields.map(()=>'?').join(',')})`).bind(h.user_id,...sourceFields.map(k=>s[k])),insertStagedCandidates(db,h.user_id,job.job_id),db.prepare('INSERT INTO v3_source_threads(user_id,collector_id,source_id,generation,thread_id,payload) SELECT user_id,collector_id,source_id,generation,thread_id,payload FROM v3_rebuild_threads WHERE user_id=? AND job_id=?').bind(h.user_id,job.job_id),...projects.statements,...await entityStatements(db,target,projects.changes),db.prepare('INSERT INTO v3_legacy_heads(user_id,device_id,dataset_id,thread_id,imported_revision,collector_id,source_id) VALUES(?,?,?,?,?,?,?) ON CONFLICT(user_id,device_id,dataset_id,thread_id) DO UPDATE SET imported_revision=excluded.imported_revision,collector_id=excluded.collector_id,source_id=excluded.source_id').bind(h.user_id,head.device_id,head.dataset_id,head.thread_id,head.revision,head.collector_id,head.source_id),...rebuildPublication(db,live,job.job_id,checkpoint.epoch),advanceHead(db,live,projects.changes.length>0),db.prepare("UPDATE v3_jobs SET payload='{}',checkpoint='{}',state='pending',lease_token=NULL,lease_until=0,next_attempt_at=0,updated_at=? WHERE user_id=? AND job_id=?").bind(Date.now(),h.user_id,job.job_id),endGuard(db,h.user_id,op));await db.batch(statements);return false;
  });
}
