import { createHash } from 'node:crypto';
import { readFileSync, readdirSync, writeFileSync, existsSync, statSync, mkdirSync, renameSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const output = 'tooling/generated/build-version.ts';
const inputs = ['bin', 'apps', 'modules', 'tooling', 'modules.json', 'cloud/migrations', 'cloud/wrangler.jsonc', 'cloud/tsconfig.deploy.json',
  'package.json', 'package-lock.json', 'cloud/package.json', 'cloud/package-lock.json',
  'vite.config.ts', 'tsconfig.json', 'tsconfig.server.json', 'tsconfig.node.json', 'tsconfig.browser.json', 'scripts/build-version.mjs', 'scripts/build-server.mjs'];
function files(relative) {
  if (!statSync(path.join(root,relative)).isDirectory()) return [relative];
  return readdirSync(path.join(root, relative), { withFileTypes: true }).flatMap(entry => {
    const next = relative + '/' + entry.name;
    return entry.isDirectory() ? files(next) : [next];
  });
}
const hash = createHash('sha256');
for (const file of inputs.flatMap(files).filter(file => !file.startsWith('tooling/generated/')).sort()) {
  // Git's Windows checkout conversion must not create a different release.
  const raw = readFileSync(path.join(root, file));
  const content = /\.(?:[cm]?[jt]sx?|jsonc?|css|html|sql|svg|ps1)$/.test(file) ? Buffer.from(raw.toString('utf8').replaceAll('\r\n','\n')) : raw;
  hash.update(file + '\0' + content.length + '\0').update(content).update('\0');
}
const version = JSON.parse(readFileSync(path.join(root, 'package.json'), 'utf8')).version;
const build = `${version}+${hash.digest('hex')}`;
const source = `// Generated by scripts/build-version.mjs. Diagnostic source fingerprint; synchronization checks modules/contracts/sync-version.ts.\nexport const BUILD_VERSION = ${JSON.stringify(build)};\nexport const PACKAGE_VERSION = ${JSON.stringify(version)};\n`;
const target = path.join(root, output);
mkdirSync(path.dirname(target), {recursive: true});
if (!existsSync(target) || readFileSync(target, 'utf8') !== source) {
  const temporary = target + '.' + process.pid + '.tmp';
  writeFileSync(temporary, source); renameSync(temporary, target);
}
console.log('Cloud/local build: ' + build);
